### CREATE
POST http://localhost:8080/api/movies
Content-Type: application/json

{
"title": "Parasite",
"director": "Bong Joon-ho",
"genre": "Drama",
"year": 2019,
"rating": 9.0,
"runningTime": 132
}

### READ ALL
GET http://localhost:8080/api/movies

### READ ONE
GET http://localhost:8080/api/movies/1

### UPDATE
PUT http://localhost:8080/api/movies/1
Content-Type: application/json

{
  "title": "Parasite",
  "director": "Bong Joon-ho",
  "genre": "Thriller",
  "year": 2019,
  "rating": 9.5,
  "runningTime": 132
}

### CHECK UPDATE
GET http://localhost:8080/api/movies/1

### DELETE
DELETE http://localhost:8080/api/movies/1

### CHECK DELETE
GET http://localhost:8080/api/movies/1

### 없는 영화 조회
GET http://localhost:8080/api/movies/999

### 잘못된 입력 테스트
POST http://localhost:8080/api/movies
Content-Type: application/json


### 영화 1 등록
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Parasite",
  "director": "Bong Joon-ho",
  "genre": "Drama",
  "year": 2019,
  "rating": 9.0,
  "runningTime": 132
}

### 영화 2 등록
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Inception",
  "director": "Christopher Nolan",
  "genre": "Sci-Fi",
  "year": 2010,
  "rating": 8.8,
  "runningTime": 148
}

### 장르 검색
GET http://localhost:8080/api/movies?genre=Drama